<?php

namespace InventoryBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FeesRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeesRepository extends EntityRepository {

	public function actionsToCalculate($id, $from, $to) {
		// Liczba usług
		$actionsQuery = $this->getEntityManager()->createQuery(
			"SELECT a.action FROM InventoryBundle:Action a WHERE a.customer = $id AND a.date BETWEEN '$from' and '$to'"
		)->getResult();

		// Lista opłat
		$feesQuery = $this->getEntityManager()->createQuery(
			"SELECT f.delivery,f.import,f.storage FROM InventoryBundle:Fees f WHERE f.customer = $id"
		)->getResult();

		$fees = $feesQuery[0];

		// Liczymy usługi (ilość przywozów i dowozów)
		$numberOfActions = [];
		foreach ($actionsQuery as $key => $value) {
	    foreach ($value as $key2 => $value2) {
        $index = $key2.''.$value2;
        if (array_key_exists($index, $numberOfActions)) {
           $numberOfActions[$index]++;
        } else {
           $numberOfActions[$index] = 1;
        }
	    }
		}
		
    if(!isset($numberOfActions['actionIn'])) {
       $numberOfActions['actionIn'] = 0;
    }
    if(!isset($numberOfActions['actionOut'])) {
       $numberOfActions['actionOut'] = 0;
    }    

		return $feesTable = array_merge($fees,$numberOfActions);
	}

}
