# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    authentication.handler.login_success_handler:
        class:  InventoryBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']

    app.form.registration:
        class: InventoryBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: InventoryBundle\Form\CustomerType
        tags:
            - { name: form.type, alias: app_user_profile }        